## Удалено, nginx для легаси пока на внешнем сервере.
---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-suggest-io
  namespace: default
spec:
  type: ExternalName
  externalName: powerdns.suggest.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powerdns-suggest-io
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/16"
spec:
  rules:
  - host: powerdns.cbca.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: powerdns-suggest-io
            port:
              number: 80
--- 
