apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: artifactory
  name: artifactory
spec:
  containers:
  - image: docker.suggest.io:5000/sio/artifactory
    name: artifactory
    ports:
    - containerPort: 8081
    resources: {}
  restartPolicy: OnFailure
status: {}
