apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: clamav
  name: clamav
spec:
  containers:
  - image: docker.suggest.io:5000/sio/clamav
    name: clamav
    resources: {}
  restartPolicy: OnFailure
status: {}
