apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: clamav
  name: clamav
spec:
  containers:
  - image: docker-registry.suggest.io/sio/clamav
    name: clamav
    resources: {}
  restartPolicy: OnFailure
status: {}
