apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: docker-registry
  name: docker-registry
spec:
  containers:
  - image: docker-registry.suggest.io/sio/docker-registry
    name: docker-registry
    ports:
    - containerPort: 5000
    resources: {}
  restartPolicy: OnFailure
status: {}
