apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  containers:
  - image: docker.suggest.io:5000/sio/elasticsearch
    name: elasticsearch
    resources: {}
  restartPolicy: OnFailure
status: {}
