apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  containers:
  - image: docker.suggest.io:5000/sio/jenkins
    name: jenkins
    ports:
    - containerPort: 8090
    resources: {}
  restartPolicy: OnFailure
status: {}
