apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  containers:
  - image: docker-registry.suggest.io/sio/kibana
    name: kibana
    ports:
    - containerPort: 5601
    resources: {}
  restartPolicy: OnFailure
status: {}
