apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: swfs-volume
  name: swfs-volume
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: swfs-volume
    spec:
      containers:
      - args:
        - volume
        - -max=15
        - -mserver=swfs-master:9333
        - -port=8081
        image: docker.suggest.io:5000/sio/seaweedfs
        name: swfs-volume
        resources: {}
      restartPolicy: Always
status: {}
