version: '2'

services:
  master:
    image: docker-registry.suggest.io:5000/sio/seaweedfs
    ports:
    - 9333:9333
    - 19333:19333
    command: "master"
  volume:
    image: docker-registry.suggest.io:5000/sio/seaweedfs
    ports:
    - 8080:8080
    - 18080:18080
    command: 'volume -max=15 -mserver="master:9333" -port=8080'
    depends_on:
    - master
  filer:
    image: docker-registry.suggest.io:5000/sio/seaweedfs
    ports:
    - 8888:8888
    - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
    - master
    - volume
  cronjob:
    image: docker-registry.suggest.io:5000/sio/seaweedfs
    command: 'cronjob'
    environment:
      # Run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
    - master
    - volume
  
