apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    "io.suggest.svc.type": "redis"
spec:
  containers:
  - name: redis-cont
    image: docker-registry.suggest.io/sio/redis:latest
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /var/lib/redis
      name: var-lib-redis
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: var-lib-redis
    emptyDir: {}
