cluster.name: sio2d

path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch

network.host: ${HOSTNAME}
node.name: ${HOSTNAME}
# TODO node.attr.rack: ${ENV...}

http.port: 9200
transport.tcp.port: 9300

http:
  cors:
    enabled: true
    allow-origin: "*"
    allow-headers: Authorization

