version: '2'

services:
  pg-master:
    build: '.'
    image: 'docker.suggest.io:5000/sio/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
     - '/var/lib/postgresql'
    expose:
     - '5432'

  pg-slave:
    build: '.'
    image: 'docker.suggest.io:5000/sio/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/var/lib/postgresql'
    expose:
     - '5432'
    links:
     - 'pg-master'

