apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-deploy
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      nodeSelector:
        io.suggest.docker-registry.here: "true"
      containers:
      - name: docker-registry-cont
        image: docker-registry.suggest.io:5000/sio/docker-registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/docker-registry
          name: var-lib-docker-registry
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: var-lib-docker-registry
        hostPath:
          path: /var/lib/containers/docker-registry
          type: DirectoryOrCreate

