apiVersion: v1
kind: Service
metadata:
  name: registry-svc
spec:
  type: ClusterIP
  selector:
    "io.suggest.svc.type": "docker-registry"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

