#!/bin/bash

set -ex

## 1. rsync с обновлениями.
rsync -e ssh -avz $(dirname $0) developer@mac:Desktop/IOS/cordova

ssh developer@mac << EOF
set -ex
cd ~/Desktop/IOS/cordova
export PATH=/usr/local/bin:$PATH
cordova run ios --device
EOF
