#!/bin/bash

set -ex

MYDIR=$(dirname $0)

## Т.к. кордова на клиенте может и не запускаться, и не работать, отработать её тут.
$MYDIR/ios-prepare

## 1. rsync с обновлениями.
rsync \
    -e ssh \
    -avz \
    --exclude="platforms/android/build" \
    --exclude="platforms/android/*/build" \
    $MYDIR \
    developer@mac:Desktop/IOS/cordova

ssh developer@mac << EOF
set -ex
cd ~/Desktop/IOS/cordova
export PATH=/usr/local/bin:$PATH
./ios-prepare
#cordova run ios --device
EOF
