version: '2'

services:

  ## seaweedfs
  swfs_master:
    image: docker.suggest.io:5000/sio/seaweedfs
    #ports:
    #- 9333:9333
    #- 19333:19333
    expose:
    - 9333
    - 19333
    command: "master"
  swfs_volume:
    image: docker.suggest.io:5000/sio/seaweedfs
    #ports:
    #- 8080:8080
    #- 18080:18080
    expose:
    - 8080
    - 18080
    command: 'volume -max=15 -mserver="swfs_master:9333" -port=8081'
    depends_on:
    - swfs_master
  swfs_filer:
    image: docker.suggest.io:5000/sio/seaweedfs
    #ports:
    #- 8888:8888
    #- 18888:18888
    expose:
    - 8888
    - 18888
    command: 'filer -master="swfs_master:9333"'
    tty: true
    stdin_open: true
    depends_on:
    - swfs_master
    - swfs_volume
  swfs_cronjob:
    image: docker.suggest.io:5000/sio/seaweedfs
    command: 'cronjob'
    environment:
      # Run re-replication every N minutes
      CRON_SCHEDULE: '*/3 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: swfs_master:9333 # Default: localhost:9333
    depends_on:
    - swfs_master
    - swfs_volume
  
  ## postgresql
  pg_master:
    image: 'docker.suggest.io:5000/sio/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    expose:
     - 5432
  pg_slave:
    image: 'docker.suggest.io:5000/sio/postgresql'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      REPLICATE_FROM: 'pg_master'
    expose:
     - 5432
    links:
     - pg_master

  clamav:
    image: docker.suggest.io:5000/sio/clamav
    restart: always
    expose:
      - 3310
  
  docker_registry:
    image: docker.suggest.io:5000/sio/docker-registry
    restart: always
    expose:
      - 5000

  elasticsearch:
    image: docker.suggest.io:5000/sio/elasticsearch
    restart: always
    expose:
      - 9200
      - 9300

  jenkins:
    image: docker.suggest.io:5000/sio/jenkins
    restart: always
    ports:
      - 8090:8090
    expose:
      - 50000
    links:
      - docker_registry

  www:
    image: docker.suggest.io:5000/sio/www
    restart: always
    ports:
      - 9000:9000
    links:
      - swfs_master
      - swfs_volume
      - elasticsearch
      - clamav
      - pg_master
      - pg_slave
    depends_on:
      - swfs_master
      - swfs_volume
      - elasticsearch
      - clamav
      - pg_master
      - pg_slave

