## Образ контейнера для сборки sioweb из sbt.

FROM docker-registry.suggest.io/sio/sio2/os-base-www
LABEL maintainer="konstantin.nikiforov@cbca.ru"

## remove all useless stuff
RUN sio-finalize-container.sh

