apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  #finalizers:
  # - kubernetes.io/pv-protection
  labels:
    type: local
  name: data-ldap-sio-openldap-stack-ha-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-ldap-sio-openldap-stack-ha-0
    namespace: ldap
  hostPath:
    path: /var/lib/containers/ldap/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem

