---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: artifactory-volume-artifactory-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: artifactory-volume-artifactory-0
    namespace: artifactory-oss
  hostPath:
    path: /var/lib/containers/artifactory-oss/artifactory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: data-artifactory-postgresql-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-artifactory-postgresql-0
    namespace: artifactory-oss
  hostPath:
    path: /var/lib/containers/artifactory-oss/postgresql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: artifactory
    app.kubernetes.io/name: postgresql
    role: primary
  name: data-artifactory-postgresql-0
  namespace: artifactory-oss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
