---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-master-deploy
  labels:
    app: postgresql
    app2: postgresql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: postgresql-master
  template:
    metadata:
      labels:
        app: postgresql
        app2: postgresql-master
    spec:
      nodeSelector:
        io.suggest.postgresql.master.here: "true"
      containers:
      - name: pg-master-cont
        image: docker-registry.suggest.io:5000/sio/sio2/postgresql:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgres
          name: var-lib-postgres
        env:
        - name: POSTGRES-PASSWORD
          value: postgres
        - name: POSTGRES-USER
          value: postgres
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: var-lib-postgres
        hostPath:
          path: /var/lib/containers/postgresql
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: pg-master-svc
spec:
  type: ClusterIP
  selector:
    app2: postgresql-master
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
