apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  type: ClusterIP
  selector:
    "io.suggest.svc.type": "postgresql"
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  
