---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-slave-deploy
  labels:
    app: postgresql
    app2: postgresql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: postgresql-slave
  template:
    metadata:
      labels:
        app: postgresql
        app2: postgresql-slave
    spec:
      nodeSelector:
        io.suggest.postgresql.slave.here: "true"
      containers:
      - name: pg-slave-cont
        image: docker-registry.suggest.io:5000/sio/sio2/postgresql:20190528-1
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgres
          name: var-lib-postgres
        env:
        - name: POSTGRES-PASSWORD
          value: postgres
        - name: POSTGRES-USER
          value: postgres
        - name: REPLICATE_FROM
          value: pg-master-svc
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: var-lib-postgres
        hostPath:
          path: /var/lib/containers/postgresql
          type: DirectoryOrCreate
---
