package io.suggest.xplay.qsb

import io.suggest.common.qs.QsConstants
import play.api.mvc.QueryStringBindable


/** To reduce compiler code generation in subclasses, instead of QueryStringBindable trait,
  * this abstract class should be used.
  *
  * Also, some small suggest.io-related stuff pushed here.
  */
abstract class AbstractQueryStringBindable[T]
  extends QueryStringBindable[T]
{

  /** Use custom function for serialization of query-string value inside js-router, generated by play-framework. */
  override def javascriptUnbind: String =
    QsConstants.JSRR_OBJ_TO_QS_F

}
