## gitlab + docker-registry
## Т.к. gitlab требует доступ в недра /var/lib/docker-registry, контейнеры живут в
## одном pod'е.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      nodeSelector:
        io.suggest.gitlab.here: "true"
      containers:
      ## gitlab web
      - name: gitlab-cont
        image: docker-registry.suggest.io:5000/sio/sio2/gitlab:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/lib/gitlab
          name: var-lib-gitlab
        - mountPath: /var/lib/redis
          name: var-lib-redis
        - mountPath: /var/lib/docker-registry
          name: var-lib-docker-registry
          readOnly: true
        - name: docker-registry-creds
          mountPath: /etc/docker-registry/registry.key
          subPath: registry.key
          readOnly: true
        env:
        - name: PG_HOST
          value: postgresql-svc
        - name: PG_PASSWORD
          value: gitlab
        - name: PG_USERNAME
          value: gitlab
        - name: PG_DATABASE
          value: gitlab
      ## docker-registry
      - name: docker-registry-cont
        image: docker-registry.suggest.io:5000/sio/sio2/docker-registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: var-lib-docker-registry
          mountPath: /var/lib/docker-registry
        - name: docker-registry-creds
          mountPath: /etc/docker-registry/registry.crt
          subPath: registry.crt
          readOnly: true
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: docker-registry-creds
              key: http-secret
      ## pod params
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: var-lib-redis
        hostPath:
          path: /var/lib/containers/gitlab/redis
          type: DirectoryOrCreate
      - name: var-lib-gitlab
        hostPath:
          path: /var/lib/containers/gitlab/gitlab
          type: DirectoryOrCreate
      - name: var-lib-docker-registry
        hostPath:
          path: /var/lib/containers/docker-registry
          type: DirectoryOrCreate
      - name: docker-registry-creds
        secret:
          secretName: docker-registry-creds
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  type: ClusterIP
  selector:
    app: gitlab
  ports:
  - name: webui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: workhorse
    protocol: TCP
    port: 8282
    targetPort: 8282
  - name: docker-registry
    protocol: TCP
    port: 5000
    targetPort: 5000
---
## Ингрес для проброса gitlab-а.
## Костыли с 8282 связаны с необходимостью доступа из runner'а, а доп.HTTP-хидеры внезапно оказались не нужны.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-gitlab
spec:
  rules:
  - host: source.suggest.io
    http:
      paths:
      - path: /sio/sio2.git
        #'[-/\w.]+\.git/'
        backend:
          serviceName: gitlab-svc
          servicePort: workhorse
      - backend:
          serviceName: gitlab-svc
          servicePort: webui
  - host: docker-registry.suggest.io
    http:
      paths:
      - backend:
          serviceName: gitlab-svc
          servicePort: docker-registry

