## Если первый запуска на пустом энтерпрайзе, то система будет ждать юзера по ssh для запуска `$0 init` или `$0 initdb` .
##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deploy
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      nodeSelector:
        io.suggest.gitlab.here: "true"
      containers:
      - name: gitlab-cont
        image: docker-registry.suggest.io/sio/gitlab
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 22
        volumeMounts:
        - mountPath: /var/lib/gitlab
          name: var-lib-gitlab
        - mountPath: /var/lib/redis
          name: var-lib-redis
        env:
        - name: PG_HOST
          value: postgresql-svc
        - name: PG_PASSWORD
          value: gitlab
        - name: PG_USERNAME
          value: gitlab
        - name: PG_DATABASE
          value: gitlab
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: var-lib-redis
        hostPath:
          path: /var/lib/containers/gitlab/redis
          type: DirectoryOrCreate
      - name: var-lib-gitlab
        hostPath:
          path: /var/lib/containers/gitlab/gitlab
          type: DirectoryOrCreate

