apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  type: ClusterIP
  selector:
    "io.suggest.svc.type": "gitlab"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: webui
  - protocol: TCP
    port: 22
    targetPort: 22
    name: ssh
