apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  type: ClusterIP
  selector:
    app: gitlab
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: webui
  - protocol: TCP
    port: 22
    targetPort: 22
    name: ssh
  - protocol: TCP
    port: 8282
    targetPort: 8282
    name: workhorse
