## Ингрес для проброса gitlab-а.
## Костыли с 8282 связаны с необходимостью доступа из runner'а, а доп.HTTP-хидеры внезапно оказались не нужны.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-gitlab
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      ;proxy_set_header    X-Real-IP           $remote_addr;
      ;proxy_set_header    X-Forwarded-Ssl     on;
      ;proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
      ;proxy_set_header    X-Forwarded-Proto   https;
      ;proxy_redirect      off;
spec:
  rules:
  - host: source.suggest.io
    http:
      paths:
      - path: /suggestio/sio2.git
        #'[-/\w.]+\.git/'
        backend:
          serviceName: gitlab-svc
          servicePort: 8282
      - backend:
          serviceName: gitlab-svc
          servicePort: 8080

