## SSH port 222 via nginx-ingress tcp-forwarding.
## !!! Ensure configMap patched properly (222 replaces 22) by hands using:
##   kubectl edit cm gitlab-nginx-ingress-tcp -n gitlab-ce
##
## After update, need to check nginx-ingress args at:
## $ kubectl -n ingress-nginx edit deploy
## List of args in spec/template/spec/container/args:
## Ensure line appended:
##          - --tcp-services-configmap=default/tcp-services
##
## If pod shows no ports on node available, delete old pod manually:
## kubectl delete pod -n ingress-nginx ingress-nginx-controller-769b74758f-kz4bn
## https://github.com/kubernetes/ingress-nginx/issues/4626
##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-nginx-ingress-tcp
  namespace: gitlab-ce
data:
  "222": "gitlab-ce/gitlab-gitlab-shell:22"
---
