## Проброс ssh через 222 порт tcp - ingress.
#
## !!! После заливки этого файла, надо:
## $ kubectl -n ingress-nginx edit deploy
## И в список spec/template/spec/container/args дописать строку:
##          - --tcp-services-configmap=default/tcp-services
##
## If pod shows no ports on node available, delete old pod manually:
## kubectl delete pod -n ingress-nginx ingress-nginx-controller-769b74758f-kz4bn
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
  222:  "default/gitlab-svc:ssh"
---
